export const WORDS = [
    'apple', 'banana', 'cat', 'dog', 'elephant', 'fish', 'giraffe', 'house', 'ice cream', 'jungle',
    'kangaroo', 'lion', 'mountain', 'notebook', 'orange', 'penguin', 'queen', 'robot', 'sun', 'tree',
    'umbrella', 'violin', 'whale', 'xylophone', 'yacht', 'zebra', 'airplane', 'bicycle', 'cactus',
    'dolphin', 'egg', 'flower', 'guitar', 'helicopter', 'island', 'jacket', 'kite', 'lemon', 'moon',
    'ninja', 'owl', 'pizza', 'quilt', 'rocket', 'star', 'tiger', 'unicorn', 'volcano', 'watch',
    'x-ray', 'yo-yo', 'zombie', 'anchor', 'balloon', 'camera', 'desert', 'eagle', 'forest', 'ghost',
    'hammer', 'ink', 'jellyfish', 'koala', 'lighthouse', 'mushroom', 'nest', 'ocean', 'piano',
    'quiver', 'rainbow', 'snake', 'telescope', 'underwater', 'vampire', 'waterfall', 'window',
    'yoga', 'zigzag', 'feather', 'globe', 'candle', 'drum', 'envelope', 'fountain', 'golf', 'honey',
    'key', 'ladder', 'mirror', 'necklace', 'octopus', 'parrot', 'river', 'sailboat', 'tornado',
    'universe', 'vase', 'windmill', 'xenon', 'bag', 'book', 'chair', 'table', 'phone', 'bottle',
    'plate', 'spoon', 'fork', 'bed', 'door', 'shoe', 'shirt', 'pants', 'hat', 'clock', 'car', 'bus',
    'train', 'boat', 'road', 'bridge', 'park', 'school', 'hospital', 'shop', 'farm', 'garden',
    'beach', 'cloud', 'rain', 'snow', 'fire', 'leaf', 'grass', 'cake', 'bread', 'burger', 'milk',
    'juice', 'coffee', 'tea', 'cheese', 'mouse', 'rabbit', 'duck', 'frog', 'horse', 'monkey',
    'panda', 'bear', 'sheep', 'goat', 'pig', 'truck', 'traffic light', 'gift', 'coin', 'bell',
    'flag', 'map', 'rope', 'brush', 'soap', 'bucket', 'fan', 'pillow', 'blanket', 'ball', 'bat',
    'helmet', 'starfish', 'shell', 'crab', 'snowman', 'glasses', 'ring', 'crown', 'cookie', 'fries',
    'sandwich', 'popcorn', 'watermelon', 'strawberry', 'banana peel', 'campfire', 'stairs', 'fence',
    'mailbox', 'newspaper', 'present', 'ticket', 'diamond', 'heart', 'smile', 'thumbs up', 'hug',
    'high five', 'clap', 'wave', 'wink', 'yawn', 'sneeze', 'cough',

    'alligator', 'ant', 'bee', 'butterfly', 'camel', 'chicken', 'cow', 'deer', 'donkey', 'flamingo',
    'fox', 'goose', 'gorilla', 'hamster', 'hippo', 'leopard', 'ostrich', 'peacock', 'pelican',
    'polar bear', 'puppy', 'kitten', 'raccoon', 'shark', 'snail', 'spider', 'squirrel', 'swan',
    'turkey', 'turtle', 'walrus', 'wolf', 'worm', 'buffalo', 'cheetah', 'chameleon', 'crocodile',
    'dinosaur', 'hedgehog', 'ladybug', 'seal', 'otter', 'beaver', 'seahorse', 'jaguar', 'hyena',
    'zookeeper', 'gorilla', 'reindeer', 'donkey', 'parrot', 'canary', 'woodpecker', 'penguin chick',
    'lizard', 'snake charmer', 'scorpion', 'lobster', 'shrimp', 'clam', 'jellyfish',

    'pancakes', 'waffle', 'donut', 'cupcake', 'pasta', 'noodles', 'rice', 'sushi', 'taco', 'hot dog',
    'steak', 'bacon', 'sausage', 'pretzel', 'pudding', 'pie', 'toast', 'cereal', 'carrot', 'potato',
    'tomato', 'onion', 'corn', 'peas', 'broccoli', 'cucumber', 'pineapple', 'mango', 'grapes',
    'cherry', 'peach', 'pear', 'coconut', 'avocado', 'pumpkin', 'chocolate', 'candy', 'lollipop',
    'pizza slice', 'ice cream cone', 'birthday cake', 'jam', 'jelly', 'salad', 'soup', 'popcorn box',
    'french toast', 'mashed potatoes', 'french fries', 'cheesecake', 'brownie', 'marshmallow',
    'watermelon slice', 'fruit bowl', 'sandwich maker', 'frying pan', 'cooking pot', 'soup bowl',
    'salt shaker', 'pepper shaker', 'ketchup bottle', 'mustard bottle', 'honey jar', 'milk carton',
    'juice box', 'tea kettle', 'coffee mug', 'chopsticks', 'rolling pin',

    'television', 'remote', 'laptop', 'computer', 'keyboard', 'headphones', 'charger', 'lamp',
    'sofa', 'couch', 'desk', 'drawer', 'wardrobe', 'refrigerator', 'oven', 'microwave', 'toaster',
    'sink', 'bathtub', 'toilet', 'shower', 'towel', 'toothbrush', 'toothpaste', 'comb', 'hairbrush',
    'trash can', 'broom', 'mop', 'vacuum cleaner', 'iron', 'scissors', 'tape', 'glue', 'ruler',
    'pencil', 'eraser', 'marker', 'crayon', 'calculator', 'stapler', 'paper clip', 'calendar',
    'basket', 'suitcase', 'keychain', 'flashlight', 'alarm clock', 'picture frame', 'door handle',
    'light bulb', 'ceiling fan', 'curtain', 'carpet', 'rug', 'bookshelf', 'hanger', 'mirror cabinet',
    'flower pot', 'garden hose', 'toolbox', 'watering can', 'lawn mower', 'wheelbarrow', 'lantern',
    'candle holder', 'birdhouse', 'wind chime', 'shopping cart', 'piggy bank', 'music box',

    'motorcycle', 'scooter', 'skateboard', 'roller skates', 'ambulance', 'fire truck', 'police car',
    'taxi', 'tractor', 'bulldozer', 'excavator', 'submarine', 'spaceship', 'hot air balloon',
    'parachute', 'canoe', 'kayak', 'surfboard', 'cruise ship', 'minivan', 'pickup truck', 'race car',
    'monster truck', 'tram', 'trolley', 'rickshaw', 'traffic cone', 'parking meter', 'gas pump',
    'steering wheel', 'scooter helmet', 'skateboard ramp', 'boat anchor', 'fishing boat', 'canoe paddle',
    'train engine', 'train ticket', 'airplane wing', 'airplane window', 'rocket engine', 'spacesuit',

    'airport', 'library', 'restaurant', 'supermarket', 'bakery', 'museum', 'zoo', 'cinema', 'theater',
    'stadium', 'playground', 'gym', 'hotel', 'castle', 'palace', 'temple', 'church', 'mosque',
    'campground', 'police station', 'fire station', 'gas station', 'beach house', 'tree house',
    'skyscraper', 'office', 'classroom', 'laboratory', 'factory', 'warehouse', 'barn', 'train platform',
    'subway station', 'amusement park', 'water park', 'coffee shop', 'bookstore', 'flower shop',
    'pet shop', 'toy store', 'hair salon', 'farmhouse', 'lighthouse tower', 'mountain cabin',
    'swimming pool', 'basketball court', 'football field', 'tennis court', 'ice rink', 'movie theater',

    'sunset', 'sunrise', 'thunder', 'lightning', 'snowflake', 'icicle', 'lake', 'pond', 'riverbank',
    'cave', 'palm tree', 'pine tree', 'rose', 'tulip', 'sunflower', 'daisy', 'moss', 'vine',
    'acorn', 'pinecone', 'volcano eruption', 'earthquake', 'hurricane', 'rain cloud', 'snowstorm',
    'thunderstorm', 'lightning bolt', 'raindrop', 'raincoat', 'rain boots', 'sunny day',
    'cloudy sky', 'fog', 'wind', 'desert oasis', 'water lily', 'cactus flower', 'autumn tree',
    'fallen leaves', 'forest path', 'mountain cabin', 'coral reef', 'iceberg', 'glacier', 'rainbow bridge',
    'water lily pond', 'rock', 'pebble', 'sandcastle', 'seashell', 'palm forest', 'flower field',

    'doctor', 'nurse', 'teacher', 'student', 'chef', 'farmer', 'firefighter', 'police officer',
    'pilot', 'astronaut', 'soldier', 'artist', 'musician', 'singer', 'dancer', 'photographer',
    'builder', 'mechanic', 'scientist', 'detective', 'magician', 'clown', 'pirate', 'cowboy',
    'superhero', 'princess', 'king', 'wizard', 'mermaid', 'athlete', 'dentist', 'barber', 'waiter',
    'cashier', 'mail carrier', 'gardener', 'fisherman', 'lifeguard', 'judge', 'lawyer', 'programmer',
    'engineer', 'architect', 'journalist', 'reporter', 'tailor', 'plumber', 'electrician', 'carpenter',
    'firefighter helmet', 'police badge', 'doctor bag', 'chef apron',

    'football', 'soccer', 'basketball', 'cricket', 'tennis', 'baseball', 'volleyball', 'badminton',
    'hockey', 'boxing', 'swimming', 'cycling', 'running', 'skiing', 'surfing', 'skateboarding',
    'bowling', 'archery', 'karate', 'medal', 'trophy', 'football goal', 'basketball hoop',
    'tennis racket', 'baseball glove', 'golf club', 'golf ball', 'swimming goggles', 'boxing gloves',
    'soccer jersey', 'running shoes', 'gymnastics', 'table tennis', 'fencing', 'weightlifting',
    'marathon', 'relay race', 'finish line', 'skipping rope', 'jump rope', 'surfboard wave',

    'coat', 'sweater', 'scarf', 'tie', 'bow tie', 'belt', 'socks', 'boots', 'sandals', 'slippers',
    'gloves', 'dress', 'skirt', 'shorts', 'jeans', 'cap', 'sunglasses', 'earrings', 'bracelet',
    'backpack', 'handbag', 'wallet', 'pajamas', 'uniform', 'apron', 'shoelace', 'button', 'zipper',
    'pocket', 'hair clip', 'hair band', 'rain boots', 'winter coat', 'wool hat', 'leather belt',
    'wristband', 'bowler hat', 'top hat', 'cooking gloves',

    'flute', 'trumpet', 'saxophone', 'harmonica', 'ukulele', 'accordion', 'harp', 'microphone',
    'tambourine', 'maracas', 'cello', 'clarinet', 'electric guitar', 'drumstick', 'music note',
    'sheet music', 'concert stage', 'record player', 'vinyl record', 'piano stool', 'guitar pick',
    'music stand', 'drum set', 'violin bow',

    'smartphone', 'tablet', 'smartwatch', 'drone', 'game controller', 'joystick', 'USB drive',
    'hard drive', 'server', 'wifi router', 'monitor', 'printer', 'VR headset', 'battery', 'power bank',
    'smart speaker', 'webcam', 'computer screen', 'mouse pad', 'charging cable', 'game console',
    'arcade machine', 'robot vacuum', 'security camera', 'phone case', 'selfie stick', 'smart bulb',
    'flash drive', 'digital camera', 'calculator watch', 'gaming chair',

    'running', 'walking', 'jumping', 'dancing', 'swimming', 'sleeping', 'eating', 'drinking',
    'cooking', 'reading', 'writing', 'drawing', 'singing', 'laughing', 'crying', 'flying',
    'falling', 'climbing', 'fishing', 'camping', 'shopping', 'driving', 'cycling', 'skating',
    'playing guitar', 'taking a selfie', 'brushing teeth', 'washing hands', 'opening a door',
    'riding a horse', 'flying a kite', 'building a snowman', 'throwing a ball', 'catching a ball',
    'playing football', 'playing basketball', 'playing tennis', 'riding a bicycle', 'cooking dinner',
    'making coffee', 'cutting vegetables', 'washing dishes', 'watering plants', 'walking the dog',
    'taking a photo', 'using a computer', 'talking on the phone', 'opening a gift', 'blowing candles',
    'blowing bubbles', 'flying a plane', 'driving a car', 'rowing a boat', 'shaking hands',
    'giving a hug', 'waving goodbye', 'wearing sunglasses', 'tying shoelaces', 'reading a book',
    'writing a letter', 'painting a wall', 'planting a tree', 'building a house', 'riding a scooter',

    'dragon', 'fairy', 'witch', 'alien', 'monster', 'werewolf', 'magic wand', 'treasure chest',
    'pirate ship', 'crystal ball', 'magic potion', 'castle tower', 'fairy wings', 'dragon egg',
    'unicorn horn', 'mermaid tail', 'wizard hat', 'witch hat', 'pirate hat', 'superhero cape',
    'hero mask', 'robot arm', 'alien spaceship', 'haunted castle', 'enchanted forest', 'magic carpet',
    'flying broom', 'treasure map', 'golden crown', 'secret door', 'giant spider', 'sea monster',
    'fairy house', 'dragon cave', 'wizard tower', 'alien planet', 'space portal', 'magic mirror',

    'birthday', 'wedding', 'party', 'concert', 'picnic', 'camping trip', 'traffic jam',
    'traffic accident', 'rainy day', 'snow day', 'beach vacation', 'road trip', 'school bus',
    'birthday party', 'treasure hunt', 'sleepover', 'fireworks', 'parade', 'circus', 'haunted house',
    'space station', 'time machine', 'rocket launch', 'movie night', 'family dinner', 'barbecue',
    'house party', 'school trip', 'graduation', 'exam', 'holiday', 'vacation', 'shopping trip',
    'costume party', 'surprise party', 'camping night', 'beach party', 'talent show', 'school dance',
    'sports day', 'award ceremony', 'wedding cake', 'birthday invitation', 'party balloons',

    'keyhole', 'lock', 'doorbell', 'hourglass', 'magnifying glass', 'binoculars', 'compass',
    'toy car', 'toy train', 'toy robot', 'toy sword', 'marble', 'dice', 'playing cards',
    'chess board', 'puzzle', 'dominoes', 'kite string', 'rubber band', 'paper boat', 'paper crown',
    'snow globe', 'toy airplane', 'toy dinosaur', 'spinning top', 'jack-in-the-box', 'rubber duck',
    'bubble wand', 'slingshot', 'paper clip chain', 'cardboard box', 'gift ribbon', 'wrapping paper',

    'christmas tree', 'santa claus', 'stocking', 'reindeer', 'sleigh', 'christmas lights',
    'gingerbread man', 'candy cane', 'snowflake ornament', 'christmas gift', 'elf', 'north pole',
    'halloween mask', 'halloween pumpkin', 'witch broom', 'valentines card', 'love letter',
    'firecracker', 'birthday candle', 'confetti', 'balloon arch', 'party decoration', 'easter basket',
    'easter bunny', 'new year clock', 'holiday wreath', 'mistletoe', 'snowman family',

    'circle', 'square', 'triangle', 'rectangle', 'spiral', 'arrow', 'star shape', 'heart shape',
    'cross', 'check mark', 'question mark', 'exclamation mark', 'maze', 'diamond shape', 'oval',
    'hexagon', 'pentagon', 'crescent moon', 'curved line', 'straight line', 'broken line',
    'dotted line', 'target', 'bullseye', 'puzzle piece', 'pattern', 'wave pattern', 'zigzag line',
    'spiral staircase', 'geometric pattern', 'labyrinth',

    'fireplace', 'chimney', 'roof', 'window box', 'fountain pen', 'ink bottle', 'paint palette',
    'paint roller', 'easel', 'canvas', 'camera tripod', 'megaphone', 'loudspeaker', 'thermometer',
    'stethoscope', 'syringe', 'bandage', 'crutch', 'wheelchair', 'cane', 'umbrella stand',
    'coat rack', 'shoe rack', 'laundry basket', 'washing machine', 'clothes dryer', 'dishwasher',
    'blender', 'kettle', 'coffee machine', 'rice cooker', 'pressure cooker', 'cutting board',
    'knife', 'whisk', 'spatula', 'ladle', 'forklift', 'construction crane', 'tool belt',
    'measuring tape', 'hammer drill', 'screwdriver', 'wrench', 'nail', 'screw',

    'firefly', 'ladybug house', 'bird feeder', 'bird cage', 'fish tank', 'aquarium', 'pet bowl',
    'dog collar', 'cat toy', 'horse saddle', 'cow bell', 'chicken coop', 'beehive', 'ant hill',
    'spider web', 'butterfly net', 'fishing net', 'fishing rod', 'fishing hook', 'camping tent',
    'sleeping bag', 'camping lantern', 'hiking boots', 'walking stick', 'backpack tent', 'compass map',

    'detective hat', 'magnifying detective', 'secret agent', 'bank robber', 'superhero landing',
    'pirate treasure', 'knight armor', 'princess dress', 'king throne', 'wizard spell',
    'witch potion', 'dragon fire', 'alien invasion', 'robot dance', 'monster footprint',
    'ghost house', 'vampire castle', 'werewolf moon', 'mermaid treasure', 'fairy garden',

    'traffic policeman', 'school teacher', 'bus driver', 'train conductor', 'flight attendant',
    'news reporter', 'street musician', 'food delivery', 'pizza delivery', 'mail delivery',
    'construction worker', 'road worker', 'lifeguard tower', 'street vendor', 'ice cream seller',
    'fruit seller', 'shopkeeper', 'cashier counter', 'restaurant waiter', 'hotel receptionist',

    'sleeping cat', 'jumping dog', 'flying bird', 'running horse', 'swimming fish', 'climbing monkey',
    'dancing bear', 'eating elephant', 'fishing penguin', 'riding elephant', 'walking dinosaur',
    'flying dragon', 'chasing butterfly', 'feeding birds', 'petting dog', 'washing a car',
    'washing a dog', 'feeding a cat', 'milking a cow', 'riding a camel', 'walking like a robot',

    'broken umbrella', 'broken pencil', 'broken chair', 'broken window', 'empty bottle',
    'full suitcase', 'open book', 'closed book', 'locked door', 'open treasure chest',
    'spilled milk', 'melting ice cream', 'burning candle', 'popped balloon', 'lost key',
    'missing sock', 'wet floor', 'slippery banana', 'tangled headphones', 'flat tire',
    'broken guitar', 'cracked mirror', 'empty wallet', 'full backpack', 'messy room',

    'desert island', 'snowy mountain', 'tropical beach', 'deep ocean', 'dark forest', 'rocky cave',
    'flower garden', 'apple orchard', 'corn field', 'sunflower field', 'frozen lake', 'river valley',
    'mountain waterfall', 'volcano island', 'underwater city', 'space planet', 'moon surface',
    'cloud castle', 'rainbow valley', 'forest waterfall',

    'bookworm', 'early bird', 'couch potato', 'busy bee', 'night owl', 'lucky star',
    'piece of cake', 'break the ice', 'cold feet', 'green thumb', 'big fish', 'sweet tooth',
    'head in the clouds', 'raining cats', 'walking on eggshells', 'time flies', 'heart of gold',
    'king of the jungle', 'needle in a haystack', 'fish out of water'
];

export const getRandomWords = (count: number): string[] => {
    const shuffled = [...WORDS].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
};
